[package]
name = "clipak-builder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clipak-core = { path = "../clipak-core" }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
walkdir.workspace = true
sha2.workspace = true
hex.workspace = true
tracing.workspace = true
uuid.workspace = true
